### ISSUE TITLE
Get contacts

### ISSUE THREAD

**Issue by secofeixo** [flickr/flickr-sdk#10]
Hi,

I'm trying to get contacts of the user authenticated, but I have not found any function related how to get them. Is there any way to get them? The user is authenticated using token, and token secret.

Best to all

**Comment by alex-seville** [comment]
That functionality is not currently implement, but it can be added by adding it to the swagger definition!

If you added this:
https://www.flickr.com/services/api/flickr.contacts.getList.html

to this:
https://github.com/flickr/flickr-api-swagger/tree/master/schema/paths

and submitted a PR we'd be one step closer!

**Comment by alex-seville** [comment]
The next version of the API will better support currently unsupported endpoints. Stay tuned.
