### ISSUE TITLE
flickr.groups.pools.add

### ISSUE THREAD

**Issue by ebisbe** [flickr/flickr-sdk#123]
I'm getting a message 'Content not allowed' with status code 8 from pools.add. 

Can you elaborate on whats happening? It's not in the docs https://www.flickr.com/services/api/flickr.groups.pools.add.html

**Comment by alex-seville** [comment]
Photos on Flickr can have content types associated with them:
https://help.yahoo.com/kb/flickr-for-desktop/sln15848.html

Certain groups can restrict the content types allowed in their pools.

For instance, https://www.flickr.com/groups/projectweather/
This group (if you scroll down) supports only Photos and Images.

**Comment by ebisbe** [comment]
thanks @alex-seville
