### ISSUE TITLE
Extras from method?

### ISSUE THREAD

**Issue by ebisbe** [flickr/flickr-sdk#126]
Hello, 

I saw thanks to another issue posted here that the flickr api docs are a bit outdated. I'd like to know what params we can use in https://www.flickr.com/services/api/flickr.groups.search.html

I'm trying to get the throttle from the groups. Is it possible or I have to join the group to get that from https://www.flickr.com/services/api/flickr.people.getGroups.html

Thanks

**Comment by alex-seville** [comment]
I suspect you'll need to do a subsequent query after the search to get the throttle for the specific group.

By the way, the best way to get answers to questions about the API itself is to post on the Flickr API group on Flickr: https://www.flickr.com/groups/api
