### ISSUE TITLE
Parameter Request

### ISSUE THREAD

**Issue by ebisbe** [flickr/flickr-sdk#128]
Can you add the Opt in opt out in this request https://www.flickr.com/services/api/flickr.people.getGroups.html ?

I find very annoying ( for me and for you ) having to do another request for each group I want to know if they are opted out. 
You could add it in the `extras` I'll be very happy about it.

**Comment by ebisbe** [comment]
@superic ?

**Comment by superic** [comment]
Do you mean to see if the user is opted out of the Groups beta?

**Comment by ebisbe** [comment]
Nope.
Here [Groups api](https://www.flickr.com/services/api/explore/flickr.groups.getInfo) we can get the photo_limit_opt_out property of a group. To see if the group has opted out of the limit a photo can be shared to a group. 
I'd like to know if I can get that property in 
[GetGroups](https://www.flickr.com/services/api/flickr.people.getGroups.html) and (GroupSearch)[https://www.flickr.com/services/api/flickr.groups.search.html].

I'm implementing a GraphQl with Flickr and it's annoying needing to do 1 additional query for each group I get in any result just to get that parameter.

For what I see from the flickr website the GroupSearch has a lot of parameters that are added in the response but none of them are listed in the docs. In another issue you recommended me to try things because the docs are outdated so I've been trying but without any luck...

I don't think that kind of petition belongs to the Api Group in flickr because it's dead... But I'm not sure who I should ask to do it...

**Comment by alex-seville** [comment]
@ebisbe we don't index that setting in our search engine, so it can't be exposed via those APIs.

**Comment by ebisbe** [comment]
Hello @alex-seville, I don't want to open onther issue because it's realted to missing params from the queries. 

Is the 'invitation_only' param from the Groups available somewhere?

**Comment by alex-seville** [comment]
I suspect not, these group attributes that you are referencing are more associated with the Flickr product. 

As an aside, you may want to check out the API TOS just to ensure that whatever you're building, and the way you're building it, are compliant:
https://www.flickr.com/help/terms/api

**Comment by ebisbe** [comment]
@alex-seville I suspect that when you say that:
> these groups attributes that you are referencing are more associated with the Flickr product

do you mean that they are private for Flickr use only. 
I think it's very confusing then having a public api call that let's you join a group and another to ask to join a 'invitation_only' group but not having a real way to know if a group is 'invitation_only'...

And as far as I know my product is API compliant but I don't think anyone will review it ever...
