### ISSUE TITLE
Migration guide from flickrapi

### ISSUE THREAD

**Issue by andrewharvey** [flickr/flickr-sdk#133]
`flickrapi` has options for passing and API key + secret eg. https://github.com/Pomax/node-flickrapi#no-authentication-public-api-only but the README for flickr-sdk doesn't show how to do this, it would be helpful to see an example of how to do this with flickr-sdk.

**Comment by jeremyruppel** [comment]
Different ways to auth, including just public API access, are documented [in the README](https://github.com/flickr/flickr-sdk#new-flickrauth).
