### ISSUE TITLE
Additional params not sent with file upload

### ISSUE THREAD

**Issue by henrydawson** [flickr/flickr-sdk#54]
When performing a file upload, the additional parameters don't seem to be sent. The file uploads correctly, but no additional information (e.g. `title`, `tags`, etc ) gets through. I'm running on Node 6

``` 
flickr
  .request( token, secret )
  .media()
  .post(  {
    photo: "path/to/file.jpg",
    title: "My title",
    description: "Custom description",
    tags: "beach sun"
 } )
```

**Comment by jeremyruppel** [comment]
Hey @henrydawson! Sorry it took so long to get back to you. I'm fairly certain the current version of our SDK doesn't support passing those additional params through uploads. However, we've been working hard on a [major release][1] of this module and I know for a fact it supports these additional params on uploads. Would you mind giving it a look and see if it works for you?

``` 
$ npm install flickr-sdk@next
```

[1]: https://github.com/flickr/flickr-sdk/tree/next

**Comment by jeremyruppel** [comment]
We've finally released the next version of our sdk! You can find the current version on the [2.x] branch, but I can confirm upload params are included as expected in the new version. Here's [a working example][example] for uploads with additional fields.

I'm going to close this out for now, but feel free to reopen this if the new version still isn't working as expected.

[2.x]: https://github.com/flickr/flickr-sdk/tree/2.x
[example]: https://github.com/flickr/flickr-sdk/blob/master/examples/upload.js
