### ISSUE TITLE
Unable to use SDK to get request token

### ISSUE THREAD

**Issue by pglockwo** [flickr/flickr-sdk#75]
when using the authentication methods on the sdk object I always get invalid_signature returned. I have tried other packages and they work to confirm my api key and secret work. Can you confirm that latest version does authenticate and there is not a bug somewhere in the hashing of the base string.

**Comment by jeremyruppel** [comment]
Hey @pglockwo! Sorry for taking so long to respond. Yep, there's likely bugs in the OAuth signing implementation of the current version of our SDK. We've been working hard on a [major release][1] of this module and I'd love it if you gave it a look and see if it fixes your issues.

``` 
$ npm install flickr-sdk@next
```

[1]: https://github.com/flickr/flickr-sdk/tree/next

**Comment by jeremyruppel** [comment]
We've finally released the next version of our sdk! You can find the current version on the [2.x] branch, but I can confirm OAuth signing works as expected in the new version. Here's [a working example][example] for the whole OAuth flow. 

I'm going to close this out for now, but feel free to reopen this if the new version still isn't working as expected.

[2.x]: https://github.com/flickr/flickr-sdk/tree/2.x
[example]: https://github.com/flickr/flickr-sdk/blob/master/examples/oauth.js
